#!/usr/bin/sh

python comet/train/run_translation.py \
    --model_name_or_path /home/pouramini/pret/mt5-small \
    --source_lang en \
    --target_lang fa \
    --source_prefix "Translate English to Persian: " \
    --train_file data/ted_en_fa_train.json \
    --validation_file data/ted_en_fa_test.json \
    --test_file data/ted_en_fa_test.json \
    --output_dir output_trans_t5_small \
    --per_device_train_batch_size=8 \
    --per_device_eval_batch_size=8 \
    --predict_with_generate \
    --save_total_limit=4 \
    --save_steps=5000 \
    --do_eval \
    --max_eval_samples=100 \
    --max_source_length=80 \
    --max_target_length=80 \
    --val_max_target_length=80 \
    --do_predict \
    --max_predict_samples=100 \
    --do_train \
    --predict_with_generate \
    --overwrite_output_dir
#    --max_steps=20000 \
#    --max_train_samples=20000 \


# Other options

#--load_best_model_at_end=True \
